Repository Lotte-SweetPotatos/WARr-Cinema, pull requests merged in 2022-07, with the labels that each got.

#6 chore: 기존 폴더 삭제
  warr-cinema/.project
Labels: 설정

#5 docs: DB 설계 및 ERD 작성
  docs/db수정.txt
  docs/erd.PNG
  docs/규칙.txt
Labels: 문서

#11 feat: 회원가입 기능 구현
  Lotte_SweetPatatos_Warr-Cinema/WebContent/index.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/member/signup.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/main.jsp
  Lotte_SweetPatatos_Warr-Cinema/src/dao/MemberDao.java
  Lotte_SweetPatatos_Warr-Cinema/src/dto/MemberDto.java
  Lotte_SweetPatatos_Warr-Cinema/src/member/MemberController.java
Labels: 기능

#14 feat: 로그인 기능 구현
  Lotte_SweetPatatos_Warr-Cinema/WebContent/member/login.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/member/signup.jsp
  Lotte_SweetPatatos_Warr-Cinema/src/dao/MemberDao.java
  Lotte_SweetPatatos_Warr-Cinema/src/dto/MemberDto.java
  Lotte_SweetPatatos_Warr-Cinema/src/member/MemberController.java
Labels: 기능

#13 Feature/crawling
  Lotte_SweetPatatos_Warr-Cinema/WebContent/index.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/detail.jsp
  Lotte_SweetPatatos_Warr-Cinema/src/crawling/Crawling.java
  Lotte_SweetPatatos_Warr-Cinema/src/crawling/DataController.java
  Lotte_SweetPatatos_Warr-Cinema/src/dao/MovieDao.java
  Lotte_SweetPatatos_Warr-Cinema/src/db/DBConnection.java
  Lotte_SweetPatatos_Warr-Cinema/src/dto/MovieDto.java
  Lotte_SweetPatatos_Warr-Cinema/src/member/MemberController.java
  Lotte_SweetPatatos_Warr-Cinema/src/movie/MovieController.java
Labels: 기능

#18 feat: 로그인, 회원가입 페이지 스타일 적용, 회원가입 버그 해결
  Lotte_SweetPatatos_Warr-Cinema/WebContent/assets/css/style.css
  Lotte_SweetPatatos_Warr-Cinema/WebContent/assets/js/script.js
  Lotte_SweetPatatos_Warr-Cinema/WebContent/index.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/member/login.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/member/signup.jsp
  Lotte_SweetPatatos_Warr-Cinema/src/dao/MemberDao.java
  Lotte_SweetPatatos_Warr-Cinema/src/member/MemberController.java
  Lotte_SweetPatatos_Warr-Cinema/src/movie/MovieController.java
Labels: 버그, 기능

#16 feat: detail.jsp구현, MovieController의 detail부분 구현
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/detail.jsp
  Lotte_SweetPatatos_Warr-Cinema/src/crawling/Crawling.java
  Lotte_SweetPatatos_Warr-Cinema/src/crawling/DataController.java
  Lotte_SweetPatatos_Warr-Cinema/src/dao/MovieDao.java
  Lotte_SweetPatatos_Warr-Cinema/src/movie/MovieController.java
Labels: 기능

#20 feat: MainPage HTML + JSP 구현 및 서버 기능 추가
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/main.jsp
  Lotte_SweetPatatos_Warr-Cinema/src/crawling/Crawling.java
  Lotte_SweetPatatos_Warr-Cinema/src/dao/MovieDao.java
  Lotte_SweetPatatos_Warr-Cinema/src/dto/MovieDto.java
  Lotte_SweetPatatos_Warr-Cinema/src/member/MemberController.java
  Lotte_SweetPatatos_Warr-Cinema/src/movie/MovieController.java
  Lotte_SweetPatatos_Warr-Cinema/src/movie/testMain.java
Labels: 기능

#23 feat: 상세보기 페이지 스타일 적용
  Lotte_SweetPatatos_Warr-Cinema/WebContent/assets/css/style.css
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/detail.jsp
Labels: 기능

#22 Feature/detail
  Lotte_SweetPatatos_Warr-Cinema/WebContent/member/login.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/detail.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/main.jsp
  Lotte_SweetPatatos_Warr-Cinema/src/crawling/DataController.java
  Lotte_SweetPatatos_Warr-Cinema/src/member/MemberController.java
  Lotte_SweetPatatos_Warr-Cinema/src/movie/MovieController.java
Labels: 리팩토링

#26 feat: 메인페이지 스타일 적용
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/detail.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/main.jsp
  Lotte_SweetPatatos_Warr-Cinema/src/movie/MovieController.java
Labels: 기능

#27 refactor: movieDao및 testMain 수정
  Lotte_SweetPatatos_Warr-Cinema/src/dao/MovieDao.java
  Lotte_SweetPatatos_Warr-Cinema/src/movie/testMain.java
Labels: 리팩토링

#30 feat: 영화 예매 기능 구현
  Lotte_SweetPatatos_Warr-Cinema/.classpath
  Lotte_SweetPatatos_Warr-Cinema/.project
  Lotte_SweetPatatos_Warr-Cinema/WebContent/css/calendar.css
  Lotte_SweetPatatos_Warr-Cinema/WebContent/index.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/ticket.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/test.jsp
  Lotte_SweetPatatos_Warr-Cinema/src/crawling/DataController.java
  Lotte_SweetPatatos_Warr-Cinema/src/dao/MovieDao.java
  Lotte_SweetPatatos_Warr-Cinema/src/dao/RunningDao.java
  Lotte_SweetPatatos_Warr-Cinema/src/dao/TicketDao.java
  Lotte_SweetPatatos_Warr-Cinema/src/db/DBConnection.java
  Lotte_SweetPatatos_Warr-Cinema/src/dto/MovieDto.java
  Lotte_SweetPatatos_Warr-Cinema/src/dto/RunningDto.java
  Lotte_SweetPatatos_Warr-Cinema/src/member/MemberController.java
  Lotte_SweetPatatos_Warr-Cinema/src/movie/MovieController.java
Labels: 버그, 기능

#32 feat: merge conflict 해결
  Lotte_SweetPatatos_Warr-Cinema/WebContent/member/login.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/member/mypage.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/main.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/ticket.jsp
  Lotte_SweetPatatos_Warr-Cinema/src/dto/MovieDto.java
  Lotte_SweetPatatos_Warr-Cinema/src/member/MemberController.java
  Lotte_SweetPatatos_Warr-Cinema/src/movie/MovieController.java
  Lotte_SweetPatatos_Warr-Cinema/src/movie/testMain.java
Labels: 기능, 리팩토링

#34 feat: 영화 관련 페이지에 스타일 적용 및 기능 수정
  Lotte_SweetPatatos_Warr-Cinema/WebContent/WEB-INF/web.xml
  Lotte_SweetPatatos_Warr-Cinema/WebContent/assets/css/style.css
  Lotte_SweetPatatos_Warr-Cinema/WebContent/assets/images/background.jpg
  Lotte_SweetPatatos_Warr-Cinema/WebContent/assets/js/script.js
  Lotte_SweetPatatos_Warr-Cinema/WebContent/member/login.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/member/mypage.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/member/signup.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/detail.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/main.jsp
  Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/ticket.jsp
  Lotte_SweetPatatos_Warr-Cinema/src/crawling/Crawling.java
  Lotte_SweetPatatos_Warr-Cinema/src/crawling/DataController.java
  Lotte_SweetPatatos_Warr-Cinema/src/dao/MemberDao.java
  Lotte_SweetPatatos_Warr-Cinema/src/dao/MovieDao.java
  Lotte_SweetPatatos_Warr-Cinema/src/dto/MovieDto.java
  Lotte_SweetPatatos_Warr-Cinema/src/member/MemberController.java
  Lotte_SweetPatatos_Warr-Cinema/src/movie/MovieController.java
Labels: 기능, 리팩토링

#33 docs: movie데이터베이스 파일 추가
  docs/movie.sql
Labels: 문서

#35 docs : readme 파일 수정
  README.md
Labels: 문서

#36 Update README.md
  README.md
Labels: 문서
